version: '3'

services:
  nginx:
    image: nginx:1.19
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www:/var/www/html:cached
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker
      dockerfile: php.Dockerfile
    restart: on-failure
    volumes:
      - ./www:/var/www/html:cached

  db:
    image: mysql:8
    restart: on-failure
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql:delegated
      - ./sql:/docker-entrypoint-initdb.d:ro
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  composer:
    build:
      context: ./docker
      dockerfile: php.Dockerfile
    volumes:
      - ./www:/var/www/html:delegated
    working_dir: /var/www/html
    command: composer install -o

  nodejs:
    image: library/node:12
    volumes:
      - ./www/:/var/www/html:cached
      - ./www/node_modules:/var/www/html/node_modules:delegated
    working_dir: /var/www/html
    command: bash -c 'npm install && npm run watch-poll'

volumes:
  database:
